### ISSUE TITLE
Invalid json...

### ISSUE THREAD

**Issue by nonfxck** [lunar-ian/php-auto-steam-sales-event#1]
why,ASF runs well with same config files

**Comment by nonfxck** [comment]
i have no trade token , is it the reasaon?

**Comment by lunar-ian** [comment]
I think yes

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by lunar-ian** [comment]
yes
